# Generated by Django 4.1.13 on 2024-02-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_id',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
