# Generated by Django 4.1.13 on 2024-03-04 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='death_date',
        ),
    ]
