# Generated by Django 4.1.13 on 2024-03-05 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
