# Generated by Django 4.1.13 on 2024-03-05 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_event_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
