# Generated by Django 4.1.13 on 2024-02-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('popularity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('spotify_id', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('artist_id', models.CharField(max_length=200)),
                ('genres', models.CharField(max_length=200)),
                ('popularity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='user',
            name='genre_preferences',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='past_events',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='queer_events',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recommended_events',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='venue_preferences',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='top_artists',
            field=models.ManyToManyField(to='backend.artist'),
        ),
        migrations.AddField(
            model_name='user',
            name='top_tracks',
            field=models.ManyToManyField(to='backend.track'),
        ),
    ]
