# Generated by Django 4.1.13 on 2024-03-05 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_venue_event_venue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_id',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='backend.venue'),
        ),
    ]
