# Generated by Django 4.1.13 on 2024-03-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_event_venue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue_id',
            field=models.IntegerField(),
        ),
    ]
