# Generated by Django 4.1.13 on 2024-03-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_event_venue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_id',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='tickets_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue_identifier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
