# Generated by Django 4.1.13 on 2024-03-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_event_date_alter_event_event_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='top_artists',
        ),
        migrations.RemoveField(
            model_name='user',
            name='top_tracks',
        ),
        migrations.AddField(
            model_name='artist',
            name='users',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='track',
            name='users',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='artist',
            name='genres',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='link',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='genres',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(max_length=500),
        ),
    ]
