# Generated by Django 4.1.13 on 2024-03-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_remove_user_top_artists_remove_user_top_tracks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='how_soon',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='price_range',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
