# Generated by Django 4.1.13 on 2024-03-26 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_user_city_user_how_soon_user_price_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='how_soon',
        ),
        migrations.RemoveField(
            model_name='user',
            name='past_events',
        ),
        migrations.RemoveField(
            model_name='user',
            name='queer_events',
        ),
    ]
