# Generated by Django 4.1.13 on 2024-03-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_user_how_soon_remove_user_past_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recommended_events',
            field=models.TextField(blank=True, null=True),
        ),
    ]
