# Generated by Django 4.1.13 on 2024-03-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_alter_user_recommended_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recommended_events',
            field=models.TextField(default=''),
        ),
    ]
