# Generated by Django 4.1.13 on 2024-02-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_venue_event_venue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue_id',
            new_name='venue',
        ),
    ]
