# Generated by Django 4.1.13 on 2024-02-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_venue_id_event_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='venue',
            new_name='venue_id',
        ),
    ]
