# Generated by Django 4.1.13 on 2024-03-04 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_venue_id_event_venue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
